version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    network_mode: host
    volumes:
      - ./app/:/usr/src/app/
    # ports:
    #   - 8000:8000
    #   # - 5434:5432
    env_file: 
      - ./.env.dev
    depends_on:
      - db
    
  db:
    image: postgres:14.1-alpine
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=patrobas
      - POSTGRES_PASSWORD=patrobas2010
      - POSTGRES_DB=patrobasDB
    

volumes:
  postgres_data:

